DROP TABLE IF EXISTS AVAILABLE_CATEGORY;
CREATE TABLE AVAILABLE_CATEGORY (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME varchar(100) NOT NULL,
  AVAILABLE_CONTENT INTEGER NOT NULL,
  PRICE DOUBLE NOT NULL DEFAULT 0.0,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;